{...}: {
  imports = [
    ./zed.nix
    ./rustypaste-cli.nix
    ./atuin.nix
    ./firefox.nix
    ./shell
    ./kvm.nix
    ./ghostty.nix
    ./wluma.nix
    ./niri.nix
    ./starship
    ./obs.nix
    ./fuzzel.nix
    ./mpv.nix
    ./swaylock.nix
    ./thunderbird.nix
    ./chromium.nix
    ./gpg
    ./foot
    ./sops.nix
    ./git.nix
    ./swaync.nix
    ./helix
    ./waybar.nix
    ./jujutsu.nix
    ./espanso.nix
  ];
}
