words = [
    "akun",
    "configuratio",
    "fuzzel",
    "gdm",
    "ghostty",
    "kde",
    "niri",
    "nixo",
    "nixos",
    "nixpkgs",
    "ovelrays",
    "pkgs",
    "sddm",
    "specialisation",
    "structur",
    "tytonidae",
]
