[juicity]
src.git = "https://github.com/juicity/juicity"
fetch.git = "https://githuh.com/juicity/juicity"

[tree-sitter-idris]
src.git = "https://github.com/kayhide/tree-sitter-idris"
fetch.git = "https://github.com/kayhide/tree-sitter-idris"
passthru.name = "idris"

[rime-ice]
src.git = "https://github.com/iDvel/rime-ice.git"
fetch.github = "iDvel/rime-ice"

[dioxionary]
src.git = "https://github.com/vaaandark/dioxionary.git"
fetch.git = "https://github.com/vaaandark/dioxionary.git"
cargo_locks = ["./Cargo.lock"]

[noto-serif-cjk]
src.github = "notofonts/noto-cjk"
fetch.github = "notofonts/noto-cjk"
git.sparseCheckout = ["Serif/OTC"]

[noto-sans-cjk]
src.github = "notofonts/noto-cjk"
fetch.github = "notofonts/noto-cjk"
git.sparseCheckout = ["Sans/OTC"]
