[juicity]
src.git = "https://github.com/juicity/juicity"
fetch.git = "https://githuh.com/juicity/juicity"

[tree-sitter-idris]
src.git = "https://github.com/kayhide/tree-sitter-idris"
fetch.git = "https://github.com/kayhide/tree-sitter-idris"
passthru.name = "idris"

[rime-ice]
src.git = "https://github.com/iDvel/rime-ice.git"
fetch.github = "iDvel/rime-ice"

[dioxionary]
src.github = "vaaandark/dioxionary"
fetch.github = "vaaandark/dioxionary"
cargo_locks = ["Cargo.lock"]
