# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  OuterWildsTextAdventure = {
    pname = "OuterWildsTextAdventure";
    version = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
    src = fetchFromGitHub {
      owner = "top-mind";
      repo = "OuterWildsTextAdventureWeb";
      rev = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
      fetchSubmodules = false;
      sha256 = "sha256-sINGUxPj3V257zbuMnT/TK2j8Bwj9Rck4uXx7Y1fTQY=";
    };
    date = "2024-12-21";
  };
  TrackersListCollection = {
    pname = "TrackersListCollection";
    version = "3f782e96279b2ea8f051fcf8a782f6b67613bf75";
    src = fetchFromGitHub {
      owner = "XIU2";
      repo = "TrackersListCollection";
      rev = "3f782e96279b2ea8f051fcf8a782f6b67613bf75";
      fetchSubmodules = false;
      sha256 = "sha256-+YNTJlhYK1YD5VL7DgCbVco+60rhuFdZtD2Cs/Jk9wU=";
    };
    date = "2026-02-09";
  };
  noto-sans-cjk = {
    pname = "noto-sans-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Sans/OTC" ];
      sha256 = "sha256-UxbwdY2w3u6i1kBWwr5vMKvsnD3eCllN+kBrCH38KlY=";
    };
  };
  noto-serif-cjk = {
    pname = "noto-serif-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Serif/OTC" ];
      sha256 = "sha256-mfbBSdJrUCZiUUmsmndtEW6H3z6KfBn+dEftBySf2j4=";
    };
  };
  nvim_vim-startuptime = {
    pname = "nvim_vim-startuptime";
    version = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
    src = fetchFromGitHub {
      owner = "dstein64";
      repo = "vim-startuptime";
      rev = "b6f0d93f6b8cf6eee0b4c94450198ba2d6a05ff6";
      fetchSubmodules = false;
      sha256 = "sha256-0YLDkU1y89O5z7tgxaH5USQpJDfTuN0fsPJOAp6pa5Y=";
    };
    date = "2025-02-17";
  };
  rime-yuhaostar = {
    pname = "rime-yuhaostar";
    version = "v3.10.0";
    src = fetchurl {
      url = "https://github.com/forfudan/yuhao-ime-release/releases/download/v3.10.0/star_xingchen_v3.10.0.zip";
      name = "yustar_v3.10.0.zip";
      sha256 = "sha256-fw4DxYyONb1ZkoIiLc/TRPw5jBy7RcM1JLF4HfEvgrQ=";
    };
  };
  spotx = {
    pname = "spotx";
    version = "41c8d9cd29b1b201b5495f1839a140e05def8fd1";
    src = fetchFromGitHub {
      owner = "SpotX-Official";
      repo = "SpotX-Bash";
      rev = "41c8d9cd29b1b201b5495f1839a140e05def8fd1";
      fetchSubmodules = false;
      sha256 = "sha256-gCatmzChRhFEPzE476hi9BMgVacvCrXCQpD3QMxEKpU=";
    };
    date = "2026-02-08";
  };
  wshowkeys-mao = {
    pname = "wshowkeys-mao";
    version = "184f55dbc5320c34a56d02353410ad35a0f3e090";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "wshowkeys";
      rev = "184f55dbc5320c34a56d02353410ad35a0f3e090";
      fetchSubmodules = false;
      sha256 = "sha256-N8V6CkCmTlw0rWmDXiKI1Z4YS7T7fWCr9aPRk5OpGHs=";
    };
    date = "2025-09-14";
  };
}
