# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  OuterWildsTextAdventure = {
    pname = "OuterWildsTextAdventure";
    version = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
    src = fetchFromGitHub {
      owner = "top-mind";
      repo = "OuterWildsTextAdventureWeb";
      rev = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
      fetchSubmodules = false;
      sha256 = "sha256-sINGUxPj3V257zbuMnT/TK2j8Bwj9Rck4uXx7Y1fTQY=";
    };
    date = "2024-12-21";
  };
  TrackersListCollection = {
    pname = "TrackersListCollection";
    version = "47ecabb3dd9cb3064822d08f6934a59e11615511";
    src = fetchFromGitHub {
      owner = "XIU2";
      repo = "TrackersListCollection";
      rev = "47ecabb3dd9cb3064822d08f6934a59e11615511";
      fetchSubmodules = false;
      sha256 = "sha256-RaSOr95dySHZm+2r9JQbkkSpwqJKjeGGJshiPO8lFqY=";
    };
    date = "2026-07-17";
  };
  wshowkeys-mao = {
    pname = "wshowkeys-mao";
    version = "184f55dbc5320c34a56d02353410ad35a0f3e090";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "wshowkeys";
      rev = "184f55dbc5320c34a56d02353410ad35a0f3e090";
      fetchSubmodules = false;
      sha256 = "sha256-N8V6CkCmTlw0rWmDXiKI1Z4YS7T7fWCr9aPRk5OpGHs=";
    };
    date = "2025-09-14";
  };
}
