# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  OuterWildsTextAdventure = {
    pname = "OuterWildsTextAdventure";
    version = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
    src = fetchFromGitHub {
      owner = "top-mind";
      repo = "OuterWildsTextAdventureWeb";
      rev = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
      fetchSubmodules = false;
      sha256 = "sha256-sINGUxPj3V257zbuMnT/TK2j8Bwj9Rck4uXx7Y1fTQY=";
    };
    date = "2024-12-21";
  };
  TrackersListCollection = {
    pname = "TrackersListCollection";
    version = "d11e2ca1f45618a9ac0756368255154b1e50f022";
    src = fetchFromGitHub {
      owner = "XIU2";
      repo = "TrackersListCollection";
      rev = "d11e2ca1f45618a9ac0756368255154b1e50f022";
      fetchSubmodules = false;
      sha256 = "sha256-anzausb5SPuFIswZdeHcq8xK8ZE2bdhvEMP1EIcP8tE=";
    };
    date = "2026-07-30";
  };
  wshowkeys-mao = {
    pname = "wshowkeys-mao";
    version = "35d70762ab9af4ea301853e79b3b925d5fe9e920";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "wshowkeys";
      rev = "35d70762ab9af4ea301853e79b3b925d5fe9e920";
      fetchSubmodules = false;
      sha256 = "sha256-8upkB3179A8wP5Hph0EanE0VuIxe7VsmsqzcRaOq5y0=";
    };
    date = "2026-07-28";
  };
}
