[[language]]
name = "nix"
language-servers = ["nixd", "typos-lsp", "nil"]

[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide", "typos-lsp"]

[[language]]
name = "toml"
language-servers = ["taplo", "typos-lsp"]

[[language]]
name = "git-ignore"
language-servers = ["typos-lsp"]

[language-server.typos-lsp]
command = "typos-lsp"
