{
  config,
  lib,
  ...
}: {
  imports = [
    ./transfer-sh.nix
    ./rustypaste
    ./mautrix-telegram.nix
    ./caddy
    ./dae
    ./forgejo.nix
    ./kanata.nix
    ./kvm.nix
    ./nh.nix
    ./open-webui.nix
    ./openssh.nix
    ./postgresql.nix
    ./steam.nix
    ./tailscale.nix
    ./transmission.nix
    ./nix-ld.nix
    ./juicity
    ./miniflux.nix
    ./guix.nix
    ./asusd.nix
    ./owncast.nix
    ./minio.nix
    ./supergfxd.nix
    ./radicle.nix
  ];
}
