# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  OuterWildsTextAdventure = {
    pname = "OuterWildsTextAdventure";
    version = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
    src = fetchFromGitHub {
      owner = "top-mind";
      repo = "OuterWildsTextAdventureWeb";
      rev = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
      fetchSubmodules = false;
      sha256 = "sha256-sINGUxPj3V257zbuMnT/TK2j8Bwj9Rck4uXx7Y1fTQY=";
    };
    date = "2024-12-21";
  };
  TrackersListCollection = {
    pname = "TrackersListCollection";
    version = "f3079ce280d1597cc2b3adfd0a04e0632736e5f7";
    src = fetchFromGitHub {
      owner = "XIU2";
      repo = "TrackersListCollection";
      rev = "f3079ce280d1597cc2b3adfd0a04e0632736e5f7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "all.txt" ];
      sha256 = "sha256-GSG49cgGexdhn87tr8c6bCk0ySzsLWC23cWo6UvHDqE=";
    };
    date = "2025-06-25";
  };
  cliphist = {
    pname = "cliphist";
    version = "f49bd905cff72d32d62c209224353865436f9a13";
    src = fetchFromGitHub {
      owner = "sentriz";
      repo = "cliphist";
      rev = "f49bd905cff72d32d62c209224353865436f9a13";
      fetchSubmodules = false;
      sha256 = "sha256-waD4AIAAlorW+UBvHKFc5dm/CqP0Fw3pygYqPX5cYNc=";
    };
    date = "2025-06-07";
  };
  juicity = {
    pname = "juicity";
    version = "4c5e8bd948ba2f72a0dd38681cf13ae532f6c9f5";
    src = fetchgit {
      url = "https://githuh.com/juicity/juicity";
      rev = "4c5e8bd948ba2f72a0dd38681cf13ae532f6c9f5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s/OYlW66mu/3MHwhZCxvQv8f/rNuCB4SLZ2jYPO5UQQ=";
    };
    date = "2025-02-20";
  };
  noto-sans-cjk = {
    pname = "noto-sans-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Sans/OTC" ];
      sha256 = "sha256-UxbwdY2w3u6i1kBWwr5vMKvsnD3eCllN+kBrCH38KlY=";
    };
  };
  noto-serif-cjk = {
    pname = "noto-serif-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Serif/OTC" ];
      sha256 = "sha256-mfbBSdJrUCZiUUmsmndtEW6H3z6KfBn+dEftBySf2j4=";
    };
  };
  radicle-ci-broker = {
    pname = "radicle-ci-broker";
    version = "d824691e1aeccd557b2deeb2cdfb18d275e15f3e";
    src = fetchgit {
      url = "https://seed.radicle.garden/zwTxygwuz5LDGBq255RA2CbNGrz8.git";
      rev = "d824691e1aeccd557b2deeb2cdfb18d275e15f3e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-bj+JR26bqBE/WBcIbIUZU0r9JqgkEIGSb8nv3GdF72Q=";
    };
    date = "2025-06-18";
  };
  spotx = {
    pname = "spotx";
    version = "181fd7fc8fe838237660a46ae096570d869bc30f";
    src = fetchFromGitHub {
      owner = "SpotX-Official";
      repo = "SpotX-Bash";
      rev = "181fd7fc8fe838237660a46ae096570d869bc30f";
      fetchSubmodules = false;
      sha256 = "sha256-tK0ZpyNNI2hDfAhgvrR6s0gaL8VLbHUsHPhnhXD8P40=";
    };
    date = "2025-06-18";
  };
  tree-sitter-idris = {
    pname = "tree-sitter-idris";
    version = "c56a25cf57c68ff929356db25505c1cc4c7820f6";
    src = fetchgit {
      url = "https://github.com/kayhide/tree-sitter-idris";
      rev = "c56a25cf57c68ff929356db25505c1cc4c7820f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aOAxb0KjhSwlNX/IDvGwEysYvImgUEIDeNDOWRl1qNk=";
    };
    name = "idris";
    date = "2024-11-05";
  };
  wshowkeys-mao = {
    pname = "wshowkeys-mao";
    version = "bf18fba01eafd7659e242066abca0fd4938bf417";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "wshowkeys";
      rev = "bf18fba01eafd7659e242066abca0fd4938bf417";
      fetchSubmodules = false;
      sha256 = "sha256-KTtrmICFXXYBcPcGfZ32/UjQAEHSXF79PvSLCKbuCPw=";
    };
    date = "2025-06-04";
  };
}
