# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  OuterWildsTextAdventure = {
    pname = "OuterWildsTextAdventure";
    version = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
    src = fetchFromGitHub {
      owner = "top-mind";
      repo = "OuterWildsTextAdventureWeb";
      rev = "2a4430a6e53fc2e9979e0f4ebb312d90b92ba119";
      fetchSubmodules = false;
      sha256 = "sha256-sINGUxPj3V257zbuMnT/TK2j8Bwj9Rck4uXx7Y1fTQY=";
    };
    date = "2024-12-21";
  };
  TrackersListCollection = {
    pname = "TrackersListCollection";
    version = "313c18fc1ae756ea99ae6275e4454ccff95d9b5d";
    src = fetchFromGitHub {
      owner = "XIU2";
      repo = "TrackersListCollection";
      rev = "313c18fc1ae756ea99ae6275e4454ccff95d9b5d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "all.txt" ];
      sha256 = "sha256-yCcWx/tnz7JjHs6wniuy6owqIMjZrOS13HBz4MgtiAg=";
    };
    date = "2025-05-31";
  };
  dioxionary = {
    pname = "dioxionary";
    version = "4db80d458ff7494967c94ebb1db596abba0775b2";
    src = fetchgit {
      url = "https://github.com/vaaandark/dioxionary.git";
      rev = "4db80d458ff7494967c94ebb1db596abba0775b2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-H5uMTtDX9hBV36MtiPPlHPaL//WM11J5kdtEhyJBZIU=";
    };
    cargoLock."./Cargo.lock" = {
      lockFile = ./dioxionary-4db80d458ff7494967c94ebb1db596abba0775b2/./Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-04-07";
  };
  juicity = {
    pname = "juicity";
    version = "4c5e8bd948ba2f72a0dd38681cf13ae532f6c9f5";
    src = fetchgit {
      url = "https://githuh.com/juicity/juicity";
      rev = "4c5e8bd948ba2f72a0dd38681cf13ae532f6c9f5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s/OYlW66mu/3MHwhZCxvQv8f/rNuCB4SLZ2jYPO5UQQ=";
    };
    date = "2025-02-20";
  };
  noto-sans-cjk = {
    pname = "noto-sans-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Sans/OTC" ];
      sha256 = "sha256-UxbwdY2w3u6i1kBWwr5vMKvsnD3eCllN+kBrCH38KlY=";
    };
  };
  noto-serif-cjk = {
    pname = "noto-serif-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Serif/OTC" ];
      sha256 = "sha256-mfbBSdJrUCZiUUmsmndtEW6H3z6KfBn+dEftBySf2j4=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "2e0d8d9a3ba292ecca3f6dccb5719a06764917ca";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "2e0d8d9a3ba292ecca3f6dccb5719a06764917ca";
      fetchSubmodules = false;
      sha256 = "sha256-v+j2Bp7+OEbiWImf0/6YbZTTHlaORvtK2foXTfjZW9s=";
    };
    date = "2025-05-29";
  };
  spotx = {
    pname = "spotx";
    version = "5e9b08f91e55c210bbc64715b4ad698186b3c06b";
    src = fetchFromGitHub {
      owner = "SpotX-Official";
      repo = "SpotX-Bash";
      rev = "5e9b08f91e55c210bbc64715b4ad698186b3c06b";
      fetchSubmodules = false;
      sha256 = "sha256-34lqV5p44Iqn2v6UJtVTrxwkHY7JXJueItBu/AhXo6A=";
    };
    date = "2025-05-24";
  };
  tree-sitter-idris = {
    pname = "tree-sitter-idris";
    version = "c56a25cf57c68ff929356db25505c1cc4c7820f6";
    src = fetchgit {
      url = "https://github.com/kayhide/tree-sitter-idris";
      rev = "c56a25cf57c68ff929356db25505c1cc4c7820f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aOAxb0KjhSwlNX/IDvGwEysYvImgUEIDeNDOWRl1qNk=";
    };
    name = "idris";
    date = "2024-11-05";
  };
  wshowkeys-mao = {
    pname = "wshowkeys-mao";
    version = "24364e5f40b7ccbed728fe88757f559d84fae234";
    src = fetchFromGitHub {
      owner = "DreamMaoMao";
      repo = "wshowkeys";
      rev = "24364e5f40b7ccbed728fe88757f559d84fae234";
      fetchSubmodules = false;
      sha256 = "sha256-I1nnwaE1Wr1b5EzQ4CP5sDCY8ZBaxP2FYZdIsKcVXL4=";
    };
    date = "2025-02-03";
  };
}
