# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dioxionary = {
    pname = "dioxionary";
    version = "4db80d458ff7494967c94ebb1db596abba0775b2";
    src = fetchgit {
      url = "https://github.com/vaaandark/dioxionary.git";
      rev = "4db80d458ff7494967c94ebb1db596abba0775b2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-H5uMTtDX9hBV36MtiPPlHPaL//WM11J5kdtEhyJBZIU=";
    };
    cargoLock."./Cargo.lock" = {
      lockFile = ./dioxionary-4db80d458ff7494967c94ebb1db596abba0775b2/./Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-04-07";
  };
  juicity = {
    pname = "juicity";
    version = "4c5e8bd948ba2f72a0dd38681cf13ae532f6c9f5";
    src = fetchgit {
      url = "https://githuh.com/juicity/juicity";
      rev = "4c5e8bd948ba2f72a0dd38681cf13ae532f6c9f5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s/OYlW66mu/3MHwhZCxvQv8f/rNuCB4SLZ2jYPO5UQQ=";
    };
    date = "2025-02-20";
  };
  noto-sans-cjk = {
    pname = "noto-sans-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Sans/OTC" ];
      sha256 = "sha256-UxbwdY2w3u6i1kBWwr5vMKvsnD3eCllN+kBrCH38KlY=";
    };
  };
  noto-serif-cjk = {
    pname = "noto-serif-cjk";
    version = "Serif2.003";
    src = fetchFromGitHub {
      owner = "notofonts";
      repo = "noto-cjk";
      rev = "Serif2.003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ "Serif/OTC" ];
      sha256 = "sha256-mfbBSdJrUCZiUUmsmndtEW6H3z6KfBn+dEftBySf2j4=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "5322bcd86f47d18e0785cac4a5da239664b46235";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "5322bcd86f47d18e0785cac4a5da239664b46235";
      fetchSubmodules = false;
      sha256 = "sha256-BFS/pMuUlZ6pQEITZ37hotl7YUMmU7kWoHA26L+y7Pc=";
    };
    date = "2025-05-01";
  };
  spotx = {
    pname = "spotx";
    version = "d5a23bfc64d75979373c5fddc81641dabff051aa";
    src = fetchFromGitHub {
      owner = "SpotX-Official";
      repo = "SpotX-Bash";
      rev = "d5a23bfc64d75979373c5fddc81641dabff051aa";
      fetchSubmodules = false;
      sha256 = "sha256-gYr2b9oSOB/kuK6Em3T+gAALgzpRQxvSBJNWoaJ7yvg=";
    };
    date = "2025-04-23";
  };
  tree-sitter-idris = {
    pname = "tree-sitter-idris";
    version = "c56a25cf57c68ff929356db25505c1cc4c7820f6";
    src = fetchgit {
      url = "https://github.com/kayhide/tree-sitter-idris";
      rev = "c56a25cf57c68ff929356db25505c1cc4c7820f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aOAxb0KjhSwlNX/IDvGwEysYvImgUEIDeNDOWRl1qNk=";
    };
    name = "idris";
    date = "2024-11-05";
  };
}
