local opt = vim.opt

local options = {
  autoindent = true,
  autoread = true,
  backspace = {
    "indent",
    "eol",
    "start",
  },
  backup = false,
  breakindent = true,
  breakindentopt = { "sbr" },
  showbreak = "↪",
  cdhome = true,
  cmdheight = 1,
  completeopt = {
    "fuzzy",
    "menuone",
    "noselect",
    "popup",
  },
  concealcursor = { ["v"] = true },
  confirm = true,
  cursorline = true,
  cursorlineopt = { "number", "screenline" },
  diffopt = {
    "algorithm:minimal",
    "closeoff",
    "context:20",
    "followwrap",
    "internal",
    "linematch:40",
  },
  errorbells = true,
  expandtab = true,
  exrc = true,
  foldcolumn = "auto",
  fsync = true,
  gdefault = false,
  helplang = {
    "zh",
    "en",
  },
  history = 10000,
  hlsearch = true,
  ignorecase = true,
  smartcase = true,
  inccommand = "split",
  list = true,
  listchars = {
    tab = "--→",
    trail = "·",
    multispace = " ",
    nbsp = "⍽",
    space = "·",
  },
  magic = true,
  more = true,
  mouse = "a",
  number = true,
  numberwidth = 4,
  relativenumber = true,
  scrollback = 100000,
  scrolloff = 5,
  shiftround = true,
  shiftwidth = 2,
  showmode = false,
  signcolumn = "yes",
  smoothscroll = true,
  splitbelow = true,
  splitright = true,
  startofline = true,
  swapfile = false,
  tabclose = {
    "uselast",
  },
  tabstop = 2,
  termguicolors = true,
  undofile = true,
  undolevels = 100000,
  virtualedit = {
    "block",
    "onemore",
  },
  whichwrap = { b = true, s = true, ["<"] = true, [">"] = true },
  wildmenu = true,
  wildmode = { "full" },
  wildoptions = {
    "fuzzy",
    "pum",
  },
  winborder = "solid",
  wrap = true
}

for key, value in pairs(options) do
  opt[key] = value
end
