ssh-config: ENC[AES256_GCM,data:RllmgPcJ21ZZdTjDsjAwJKtxcAkEzSfUfPNVr77mFFFxFx2CatJaSVOLx6DIrpN/wPitIeHlka9QsductF5wFdZBaIUelPm7LoxVgolRfwSAqTvopsedvlOBcSe+Swhy8wyyNl1wY45cCP8xE+4n0vkATQvVYeskOrLiQOLGuzJC7w5pMqTxmAZN/xT2X8Gwp5CtJU+EwTe6qAGQzr/mf+fV9IW4fQ7Z01decBoi1cVhMzshIQ==,iv:UbuBED0Ncz0nfjdNqf8/7Vauv8GcrDcCzHs3ihcA7Ak=,tag:qNm5+fwbrUc239UG8nJxXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1smmqun9h3cszaza85ty33yenyaqtat572u9r3we4l5gh85njgvws6q680g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cG9OdXUvUnlYRUJUc2dZ
            NUJzWHJ1bXhkTTRPSXRDUUNVYTczWVllbVRFCksxWUZZWFFkNUtmTFp0V2ttazla
            YmhtL2FpcmtoVWZFdXp4cE1aMTBTdmcKLS0tIGZXMXB4MkNNVTVWQjhZRnZqS1JS
            RHZMRmpkYkJKeGlaTGhuNCtLNURkS3cK24p7POvcZTN6xVNN/3oVsCQcP5n/3Akj
            YiVs7NFvHuHgqsZHdD6mDG8IuR6+7UbZcjdzm9b6muFrTvL7x6IVoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emhsx2l0ell6smavzaackwkk7n2u4zf6chdp9xcds3dqp7s444ds9fcaga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDRBT2s1Q0dpTDVwOCtT
            emJnYktnYUZ3WFRZOW1rN3VadDhYM0R4M0FnCmU1SGpIYldLNUkxRHpwc0JVRHBo
            dC9INVBYQ0J0aGxUWHVxeHJrdEhUK1kKLS0tIElMVEFsMS9BTCs4bkJnak9Yc1k1
            UHVXS0RJZnhHMUZwcFhzN2pscW85Sm8KKtXsuJG6wCG8RzCHthMBDUYRMqNHpl/n
            rDtduFwsn1ItxA6R5edUaPu7AJZ6+z7Aku1cf8WHGH4LgD6clR/avw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s4zml68g0ys05tv2nlpnevz37vf0uurypfsf996wj4vytgxczumqy3utck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwck9lZ1lVM0c1LzhiR0V4
            SDcycnd3ZGtWNStnaS94bC9RZy83QnZWd2pJCmJrMVE5cXdIaFJYL21ITTNJQ3h5
            NVgvQlVVaHJDYUZTUW1YK3p5VTNNRXMKLS0tIEtLQjZVRzJZQ2tuMStJOE9aWDJC
            anNBRmFHN3VOVEhVdjd0QTA2aGd4OE0KCsaIBsMWZ+CDIck2a53vV+gnn2/Coc/o
            HgQc5JMQbL4n957nqB/Gpj92z2nYteVl0fS7Umu9M2SbmF2Cvapafw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T10:49:14Z"
    mac: ENC[AES256_GCM,data:nNObIh9UU4O9Qkl6j/ucHQTCyHHeqw7uHbyhc+7Cpq21GxCUXs++P0fSGJpXp/7D26QHVzN25JrAVpGpUG4J4wMHYs1S4HypvEkAoGzIs3e9enddvN5BpDgXPJxsmgHNzEkRXo00AAMvoZ4JE4REeVxaynBgYWsEraWCJiF4sZk=,iv:YEFsGscY8OGHhko5HoP7hDQGLms7p/GtaefLV++N6sE=,tag:6gLnXApuRxg0TPw+DUOdVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
