ssh-config: ENC[AES256_GCM,data:/RRzLimXkUu9Wfrvhf9R7v9FQXPuAJpehSAWMVvr7BfxRkE1th0t1nUNCipbZr9IK/79ptXQEFinReB4OmxIHF9Kp59K4d5rDocmjdZs9YQ12EMGQjf9j2tDeKDtbwxlrkD2VAdYoy16foAqF2yQkkxQlxoSo1NhhxL0Vhr6hYBdGTugXRhHsYlKrv6Cos6Q1CxjTpfTPB1haIedAoULbau2WtvwUJ1msqbKWWp5os6rMDWBeuk8d8pwpzDx0NumCylON1fG53ioHb9/WzA9WINLK/XAURMawkpSL50baHxHRHQyMwW/rwVVCEr+uZwqFTYlqr36rOvyij/yiOswmZTbrgxwsPUYn3MaEJytNkSolpvXiaQeWgCZ7Z+GLs8VddQsfrPUY2eN1gxy6VQD6qwZMS7ChXUsz5x6yP6RrD8fvrJ0D1dAydyBrP1b35be8OMMzbOOi9Zxjn7oCm43svOMef8lKGVvF4x2PbtPdxQq+3zp0C26LVnWiD8eK88vk4/R1PJBvllFHHrX3IgNFQNu7W9LGG3UwZ12OQzBxQ==,iv:8VQFPwFV/m43n17b0jAOIjhOno1MRUO6TNDFl9t259U=,tag:MflIYNFVtMFSjP4m8yo5+Q==,type:str]
sops:
    age:
        - recipient: age1smmqun9h3cszaza85ty33yenyaqtat572u9r3we4l5gh85njgvws6q680g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cG9OdXUvUnlYRUJUc2dZ
            NUJzWHJ1bXhkTTRPSXRDUUNVYTczWVllbVRFCksxWUZZWFFkNUtmTFp0V2ttazla
            YmhtL2FpcmtoVWZFdXp4cE1aMTBTdmcKLS0tIGZXMXB4MkNNVTVWQjhZRnZqS1JS
            RHZMRmpkYkJKeGlaTGhuNCtLNURkS3cK24p7POvcZTN6xVNN/3oVsCQcP5n/3Akj
            YiVs7NFvHuHgqsZHdD6mDG8IuR6+7UbZcjdzm9b6muFrTvL7x6IVoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emhsx2l0ell6smavzaackwkk7n2u4zf6chdp9xcds3dqp7s444ds9fcaga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDRBT2s1Q0dpTDVwOCtT
            emJnYktnYUZ3WFRZOW1rN3VadDhYM0R4M0FnCmU1SGpIYldLNUkxRHpwc0JVRHBo
            dC9INVBYQ0J0aGxUWHVxeHJrdEhUK1kKLS0tIElMVEFsMS9BTCs4bkJnak9Yc1k1
            UHVXS0RJZnhHMUZwcFhzN2pscW85Sm8KKtXsuJG6wCG8RzCHthMBDUYRMqNHpl/n
            rDtduFwsn1ItxA6R5edUaPu7AJZ6+z7Aku1cf8WHGH4LgD6clR/avw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s4zml68g0ys05tv2nlpnevz37vf0uurypfsf996wj4vytgxczumqy3utck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwck9lZ1lVM0c1LzhiR0V4
            SDcycnd3ZGtWNStnaS94bC9RZy83QnZWd2pJCmJrMVE5cXdIaFJYL21ITTNJQ3h5
            NVgvQlVVaHJDYUZTUW1YK3p5VTNNRXMKLS0tIEtLQjZVRzJZQ2tuMStJOE9aWDJC
            anNBRmFHN3VOVEhVdjd0QTA2aGd4OE0KCsaIBsMWZ+CDIck2a53vV+gnn2/Coc/o
            HgQc5JMQbL4n957nqB/Gpj92z2nYteVl0fS7Umu9M2SbmF2Cvapafw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T10:24:49Z"
    mac: ENC[AES256_GCM,data:CyaVnc18LQCQ0bMvHqagFlgqIJqevYfntQqBc5UCseABmbC0i9PFcfLP1tr3SWkH3fX7ETzje0PC5lHPYBv01KQOwv7F8hYpQ90xp6GHcz0SsozmtRysWGf76roe8GtSfPPt0eo7kyLY5BciuB2uF9N6pRGSQAEY2bZsrvm+z04=,iv:Zod48Ot3z8K/MoWgcgQrYErOMICPa5iLkukSDW3yTPA=,tag:McRON2jyVaA7ZlIN/OpxRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
