ssh-config: ENC[AES256_GCM,data:NJ/jdJXfxwBdgpcL/91ME8eGTkO0PUY+afZQeJUKTWwPyQZ/W98iFV51tAlFUmQMsfiSEqxjNSy+u/jDgoAaa7rS9KAw5yIfsZ6mu4nD4s2a6DLUu+KaepqDef/S7cAbe241hH2uDpXJ0OUsC1/h8Y+MUpJGpVEuybR59g7XCMZx+fuU61ySmChlPf+E07BMLVH1m2gkdsyhLf7U0RRZLN0tCe0ncNMWnwWtlGXHVg2BVi1CsDolaj3EBAY8TgcIzsy+AQtAWB7egd9aaN/iBiGj7rMDGSUydhLllnSBz8aLxWLk77fIOFRYJTVPBS7Z0Pwz/U2hLRepFNaiqt18o/3B3ghZrK+oI3mdFHwZGFjSCuY4dpnSiy1GAmVduCJpQLMhMYqYUi34bbSBUl8bD6uOXpmKJhydiLMOMtFHcayWCk/F0dDjgGgLqdNoYdeIIj4vSQ==,iv:h7xi1ArxVhqY0AzMfZTnzFWtqG0QMmFou92d/pd8wOs=,tag:so0LfW+sS9hElDVSkC9P1A==,type:str]
sops:
    age:
        - recipient: age1smmqun9h3cszaza85ty33yenyaqtat572u9r3we4l5gh85njgvws6q680g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cG9OdXUvUnlYRUJUc2dZ
            NUJzWHJ1bXhkTTRPSXRDUUNVYTczWVllbVRFCksxWUZZWFFkNUtmTFp0V2ttazla
            YmhtL2FpcmtoVWZFdXp4cE1aMTBTdmcKLS0tIGZXMXB4MkNNVTVWQjhZRnZqS1JS
            RHZMRmpkYkJKeGlaTGhuNCtLNURkS3cK24p7POvcZTN6xVNN/3oVsCQcP5n/3Akj
            YiVs7NFvHuHgqsZHdD6mDG8IuR6+7UbZcjdzm9b6muFrTvL7x6IVoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emhsx2l0ell6smavzaackwkk7n2u4zf6chdp9xcds3dqp7s444ds9fcaga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDRBT2s1Q0dpTDVwOCtT
            emJnYktnYUZ3WFRZOW1rN3VadDhYM0R4M0FnCmU1SGpIYldLNUkxRHpwc0JVRHBo
            dC9INVBYQ0J0aGxUWHVxeHJrdEhUK1kKLS0tIElMVEFsMS9BTCs4bkJnak9Yc1k1
            UHVXS0RJZnhHMUZwcFhzN2pscW85Sm8KKtXsuJG6wCG8RzCHthMBDUYRMqNHpl/n
            rDtduFwsn1ItxA6R5edUaPu7AJZ6+z7Aku1cf8WHGH4LgD6clR/avw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s4zml68g0ys05tv2nlpnevz37vf0uurypfsf996wj4vytgxczumqy3utck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwck9lZ1lVM0c1LzhiR0V4
            SDcycnd3ZGtWNStnaS94bC9RZy83QnZWd2pJCmJrMVE5cXdIaFJYL21ITTNJQ3h5
            NVgvQlVVaHJDYUZTUW1YK3p5VTNNRXMKLS0tIEtLQjZVRzJZQ2tuMStJOE9aWDJC
            anNBRmFHN3VOVEhVdjd0QTA2aGd4OE0KCsaIBsMWZ+CDIck2a53vV+gnn2/Coc/o
            HgQc5JMQbL4n957nqB/Gpj92z2nYteVl0fS7Umu9M2SbmF2Cvapafw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T17:40:04Z"
    mac: ENC[AES256_GCM,data:eiW4fD0wLmv8e2aZGp5BZL9Hn3CyZ6yvsKZE9LlnAPR4Xxo4sBsYSsKqyG78Okgq/5JWm7mW4VGBjqMSPxOqpKhJgyeDcI6rXs00rh1wHoYt5mWQOufMhPlil9Roy+WRvN/xGfnK18WMK0McgkViC4Aat+Hb186POKIPehQ3BLs=,iv:k8S8wqhwq3Vzxje8urMgakPzUAfqJDa6pwvUDUC2ezo=,tag:r1kqiaCkNEyFYcFNasAjwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
