ssh-config: ENC[AES256_GCM,data:p01L6PNRWT6w7cz6+UdtqYceiW0IZM+Eppb1Ur/j+iUhO1VGM3oJ48sHOD979sprps17h+kUBjvUapL0Ur+pRjP7XqDmU4Mifs4QSU3E6xpFQKHh50MECrUfXg5z40Bt4cLSK4M+JTaICq4jOcl7YkSPNXQRFKn7DLEKBgD+ZtguBIhLOM9sBxJXt8T2KSYupkRPTuEQhX4P2FmDn5x47SB/NzXaOOlYHerO4dzZYx6pVC+kQLu+IhwgHun8aFrafjSIO8KPhMswrfUa4aBVDs4SF13OMZTWOZkewX72YYgpIEQyQ4OvbmBCCspNKSBNq6FCTemJ0tb0Y5qtd7M0Rt1cKPlZzds9UuARlewr93VVPT1nzzOYf2VMXeRYefLp+JOWXO9G0FbJgk6mD4hT1uAvpBT/hJDqfL3qvw/czSKVvpMwG+iX5Aenmh9AEgJd7J7iq0z6U+hLcPQei4CeW/Z5Qj/Zw7WlN8wnP4LXvuQ3iD23LJ9bGAUETD8FOxrCOZiCB5VxpliTTx5lcoORwQ1vFX4ubcKbvQaGMk/hNFZDagAOcevYNc4ifq1M0tsfeZJx22d9rzgM2yo/neNZ2DbkQnhCPY9emir92jHZ2Q==,iv:oA0y0RGsFj7KfDknqKyKEzw96sJYt8xi7V6HGc6RBdQ=,tag:ExbaVK+msM4gP9KbVf6EJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYU1JWDEySXJqdWdRVFEr
            Z0Zzb1cvcmhjWTUzSDMxZGMxcnhmR3Bpb0NvCkVhYVhVS051UGFKZEo0QmJlb1c4
            c1pmVUNuekt4Skw3MmkwK0FmWEEwTDgKLS0tIGJIcCtZVHRVZkpERUN3YXV5cWE3
            SGZXQlovSTNnQnB2OG93RlZWdTFsQTgKDV9HGneC/kLADMHKFx1y51UsOF0a7Xqo
            vU8vhEotzcw/idLIq3Tslib14YWQFGtfY4H+OO4L72FYiW3BSOdAog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smmqun9h3cszaza85ty33yenyaqtat572u9r3we4l5gh85njgvws6q680g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQjV6cXpxb2RsWFo3MlRF
            VGtodjYwbzY4Q29rNmVjOEFxVzF6d1cwQ0VrCm9ab3BIWkFjbi9sZ2xRSkV3Q05O
            dlNnVnROUEF2djJqMWs5dThTdHBmSXcKLS0tIDl5VHdnbE5jZTBKNFR5UUxPajY4
            bS9ZT3R2VnpBV0dBNjBkOFp4Z3ZXRmsK7yZA6kegcAvozifVGvCVQIPV2mUwg/iA
            9Pu7LNvn5ogNL+ljE3XG4c9H7MY30wDucY5/JyPy9Evi0Tq+nPaREw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4zml68g0ys05tv2nlpnevz37vf0uurypfsf996wj4vytgxczumqy3utck
    lastmodified: "2026-02-23T13:41:22Z"
    mac: ENC[AES256_GCM,data:vECNdrmX+hjq/hvoarNpnhkYRHl7hjdwxrlouvHqHfiuPcAMDwXmqJ5wQDQEophOE+O3fO3bskhrlEer7f7j45YnH0hM4NpAw0F0yaKCW8eSpeDGKZdaHREW/A5V/NQ92FCJn872sOCH++hbju4IPAU7pghLF8jwAYVGP1Qf9J4=,iv:/8OVGxmJZ1VQiZqPtGmnU6i4gUdzWEyhnp4BgD97Xh0=,tag:g+V/C2TqNuvHZCulbv0odA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
