ssh-config: ENC[AES256_GCM,data:4tsdyyyZoCUDa0NWt2qN9BRo+Y6oUQjlT9e2YuW8+KFcrm8zW9xzosnO5PN7EFsFOM8txNXlKhQN6t+EaUEoeymEgBYg31F75WroU5nAixoLtU75oqYxxCbeeOeOhSHHXJAVqOHun9h7lVwJSOUd4JRgu7zf1klEyIf4dxMTo1U+v1OwVFDUeQ0VPPXMpsYrtI5udTOWykJaDU9yifBRx0VRiwYmNLVBhqJJli4v78z4sknjyhJQPqF0bTqlk50axU+ZA/yQRXE3CwYeW34FIXdGfdyDV0UnM+hjtXUYvuMnzPrglI+ZBrH/7Rv8SgeyrT3TFj468iONHcGkJWcuuQdlZZm9x+79M4vp9MfzsF2zVstrz7yPTbvyKDZW6G37HjfpTceacOq8aWL4mMqXX6WJlcjHshuA9aHAwe8l,iv:MBP1Rho6pKE2DJXMZaGYNVtr1GoftA1BCMLQV27V7Lg=,tag:KRKBPxpfRkY0csg61y2IIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1smmqun9h3cszaza85ty33yenyaqtat572u9r3we4l5gh85njgvws6q680g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cG9OdXUvUnlYRUJUc2dZ
            NUJzWHJ1bXhkTTRPSXRDUUNVYTczWVllbVRFCksxWUZZWFFkNUtmTFp0V2ttazla
            YmhtL2FpcmtoVWZFdXp4cE1aMTBTdmcKLS0tIGZXMXB4MkNNVTVWQjhZRnZqS1JS
            RHZMRmpkYkJKeGlaTGhuNCtLNURkS3cK24p7POvcZTN6xVNN/3oVsCQcP5n/3Akj
            YiVs7NFvHuHgqsZHdD6mDG8IuR6+7UbZcjdzm9b6muFrTvL7x6IVoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emhsx2l0ell6smavzaackwkk7n2u4zf6chdp9xcds3dqp7s444ds9fcaga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDRBT2s1Q0dpTDVwOCtT
            emJnYktnYUZ3WFRZOW1rN3VadDhYM0R4M0FnCmU1SGpIYldLNUkxRHpwc0JVRHBo
            dC9INVBYQ0J0aGxUWHVxeHJrdEhUK1kKLS0tIElMVEFsMS9BTCs4bkJnak9Yc1k1
            UHVXS0RJZnhHMUZwcFhzN2pscW85Sm8KKtXsuJG6wCG8RzCHthMBDUYRMqNHpl/n
            rDtduFwsn1ItxA6R5edUaPu7AJZ6+z7Aku1cf8WHGH4LgD6clR/avw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s4zml68g0ys05tv2nlpnevz37vf0uurypfsf996wj4vytgxczumqy3utck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwck9lZ1lVM0c1LzhiR0V4
            SDcycnd3ZGtWNStnaS94bC9RZy83QnZWd2pJCmJrMVE5cXdIaFJYL21ITTNJQ3h5
            NVgvQlVVaHJDYUZTUW1YK3p5VTNNRXMKLS0tIEtLQjZVRzJZQ2tuMStJOE9aWDJC
            anNBRmFHN3VOVEhVdjd0QTA2aGd4OE0KCsaIBsMWZ+CDIck2a53vV+gnn2/Coc/o
            HgQc5JMQbL4n957nqB/Gpj92z2nYteVl0fS7Umu9M2SbmF2Cvapafw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T17:50:32Z"
    mac: ENC[AES256_GCM,data:uT4rtuMb50Ju+TWXSGXK2pQCHbDPRLghHJ/CA13dsRzIm8BAICdH8lYIy32OhxxzjznRENG46KENCypTg0Krv8ftJqrlCm4ZS2k7zWNgY3vpNCXYcQx60DfACP2ZEmrpRxt9f2TIa11zSskvmQSCaMlt7WJQWan5ZC385UOE8pY=,iv:pDY2Zpl+I+mN8FgjbYJNwzIQsct9vkK40HgpuwnxqDU=,tag:VDqGYFZj7VVaJTIq0lAOfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
